config/routes.rb
Rails.application.routes.draw do


  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }


  scope '/admin' do
    resources :users
  end

  resources :roles


  root "welcome#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # scope '/admin' do
  #   resources :cinemas, except: [:show, :index]
  # end

  resources :cinemas, only: [:show, :index]
  resources :movies, only: [:show, :index]

  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy'
  end

  scope '/admin', as: 'admin' do
    resources :cinemas, except: [:show, :index]
    resources :movies, except: [:show, :index]
    resources :showplaces do
      resources :screenings
    end
  end

  resources :search, only: :get

  get "search" => "search#index"

  get "/coming_soon" => "movies#coming_soon", as: "coming_soon"
  get "/showing_now" => "movies#showing_now", as: "showing_now"

  get "/screenings/:screening_id/seats" => "seats#index", as: "book_seats"

  resources :screenings do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: :show

  get 'bookings/:booking_id/braintree/new' => "braintree#new", as: "braintree_pay"
  post 'bookings/:booking_id/braintree/checkout' => "braintree#checkout", as: "braintree_paying"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    # user ||= User.new # guest user (not logged in)
    # if user.admin?
    #   can :manage, :all
    # else
    #   can :read, :all
    # end

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  belongs_to :user
         def self.create_with_omniauth(auth_hash)
     auth = Authentication.new(provider: auth_hash["provider"], uid: auth_hash["uid"], token: auth_hash["credentials"]["token"])
  end

  def update_token(auth_hash)
    self.token = auth_hash["credentials"]["token"]
    self.save
  end
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_many :seat_bookings
  has_many :seats, through: :seat_bookings
  belongs_to :screening
  belongs_to :user

  def set_total_price(user_seats)
    total = 0
    user_seats.each do |x|
      total += x.screening.price
    end
    self.total_price = total
    self.save
  end

end

app/models/cinema.rb
class Cinema < ApplicationRecord
  has_many :showplaces
  has_many :movies, through: :showplaces
  has_many :screenings, through: :showplaces

  validates :latitude, :longitude, presence: true

  mount_uploaders :photos, CinemaPicturesUploader
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :showplaces
  has_many :cinemas, through: :showplaces
  has_many :screenings, through: :showplaces

  mount_uploaders :photos, MoviePicturesUploader
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :reservation
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users
end

app/models/screening.rb
class Screening < ApplicationRecord

  belongs_to :showplace, :dependent => :destroy
  belongs_to :movie
  belongs_to :cinema

  has_many :seats

  after_create :create_seats

  def create_seats
    rows = ("A".."R")
    nums = (1..18)
    rows.each do |row|
      nums.each do |num|
        Seat.create(screening_id: self.id, row_number: row, seat_number: num)
      end
    end
  end
end

app/models/seat.rb
class Seat < ApplicationRecord
  has_many :seat_bookings
  has_many :bookings, through: :seat_bookings
  belongs_to :screening, :dependent => :destroy

end

app/models/seat_booking.rb
class SeatBooking < ApplicationRecord
  belongs_to :seat
  belongs_to :booking
end

app/models/showplace.rb
class Showplace < ApplicationRecord
  belongs_to :movie
  belongs_to :cinema
  has_many :screenings
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]
  belongs_to :role

  validates_presence_of :username
  validates :email, uniqueness:{ message: "Your email has already been taken!"}
  validates :email, presence: { message: "You need to type in an email!"}

  def assign_role
    self.role = Role.find_by(name: "Customer") unless self.role
  end


  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.username = auth.info.name
      user.role_id = Role.find_by_name("Customer").id
        # assuming the user model has a name
      # user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end
end

app/controllers/showplaces_controller.rb
class ShowplacesController < ApplicationController

	def index
		@showplaces = Showplace.all
	end

	def new
		@showplace = Showplace.new
	end

	def create
		@showplace = Showplace.new(showplace_params)
		if @showplace.save
			redirect_to root_path
		else
			render "showplaces/new"
		end
	end

	def edit
		@showplace = Showplace.find(params[:id])
	end

	def update
		@showplace = Showplace.find(params[:id])
		if @showplace.save
			redirect_to root_path
		else
			render "showplaces/edit"
		end
	end

	def destroy
		@showplace = Showplace.find(params[:id])
		if @showplace.destroy
			redirect_to root_path
		else
			redirect_to admin_showplaces_path
		end
	end

	private
  def showplace_params
    params.require(:showplace).permit(:cinema_id, :movie_id, :hall_no)
  end


end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/braintree_helper.rb
module BraintreeHelper
end

app/helpers/cinemas_helper.rb
module CinemasHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/screenings_helper.rb
module ScreeningsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/seats_helper.rb
module SeatsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/showplaces/_form.html.erb
<p>
  <%= form.label :cinema_id %><br>
  <%= form.text_field :cinema_id %>
</p>

<p>
  <%= form.label :movie_id %><br>
  <%= form.text_area :movie_id %>
</p>

<p>
  <%= form.submit %>
</p>

app/views/showplaces/edit.html.erb
<div class="row">
  <div class-"col-md-8 col-md-offset-2 col-xs-8 col-xs-offset-2">
    <h1 class="text-center">
      Edit Showplace
    </h1>
  </div>
</div>
<div class="row">
  <div class="col-md-8 col-md-offset-2 col-xs-8 col-xs-offset-2">
    <%= form_for [:admin, @showplace] do |form| %>
      <%= render partial: 'form', object: form %>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="col-md-8 col-md-offset-2 col-xs-8 col-xs-offset-2 text-center">
    <%= link_to "Delete Movie", admin_showplace_path(@showplace), method: :delete, data: {confirmation: "Are you sure?"}, class: "btn btn-danger" %>
  </div>
</div>

<%= link_to 'Back', root_path %>

app/views/showplaces/index.html.erb
<% @showplaces.each do |showplace| %>
  <p><%=showplace.movie.title%></p>
  <p><%=showplace.cinema.cinema_name%></p>

  <td><%= link_to 'Show Screenings', admin_showplace_screenings_path(showplace), class: 'btn btn-mini btn-success' %></td>
  <td><%= link_to 'Edit', edit_admin_showplace_path(showplace), class: 'btn btn-mini btn-success' %></td>
  <td><%= link_to 'Destroy', admin_showplace_path(showplace), method: :delete, class: 'btn btn-mini btn-danger', data: { confirm: 'Are you sure?' } %></td>

<% end %>

<%= link_to 'New Showplace', new_admin_showplace_path %>
<%= link_to 'Back', root_path %>

app/views/showplaces/new.html.erb
<h1>Add Showplace</h1>


<%= form_for [:admin, @showplace] do |form| %>
  <%= form.label :cinema_name %><br>
  <%= form.collection_select :cinema_id, Cinema.order(:cinema_name),:id,:cinema_name, include_blank: true %>


  <%= form.label :movie_name %><br>
  <%= form.collection_select :movie_id, Movie.order(:title),:id,:title, include_blank: true %>
  
  <p>
    <%= form.submit %>
  </p>

<% end %>

<%= link_to 'Back', root_path %>