config/routes.rb
Rails.application.routes.draw do


  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }


  scope '/admin' do
    resources :users
  end

  resources :roles


  root "welcome#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # scope '/admin' do
  #   resources :cinemas, except: [:show, :index]
  # end

  resources :cinemas, only: [:show, :index]
  resources :movies, only: [:show, :index]

  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy'
  end

  scope '/admin', as: 'admin' do
    resources :cinemas, except: [:show, :index]
    resources :movies, except: [:show, :index]
    resources :showplaces do
      resources :screenings
    end
  end

  resources :search, only: :get

  get "search" => "search#index"

  get "/coming_soon" => "movies#coming_soon", as: "coming_soon"
  get "/showing_now" => "movies#showing_now", as: "showing_now"

  get "/screenings/:screening_id/seats" => "seats#index", as: "book_seats"

  resources :screenings do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: :show

  get 'bookings/:booking_id/braintree/new' => "braintree#new", as: "braintree_pay"
  post 'bookings/:booking_id/braintree/checkout' => "braintree#checkout", as: "braintree_paying"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    # user ||= User.new # guest user (not logged in)
    # if user.admin?
    #   can :manage, :all
    # else
    #   can :read, :all
    # end

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  belongs_to :user
         def self.create_with_omniauth(auth_hash)
     auth = Authentication.new(provider: auth_hash["provider"], uid: auth_hash["uid"], token: auth_hash["credentials"]["token"])
  end

  def update_token(auth_hash)
    self.token = auth_hash["credentials"]["token"]
    self.save
  end
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_many :seat_bookings
  has_many :seats, through: :seat_bookings
  belongs_to :screening
  belongs_to :user

  def set_total_price(user_seats)
    total = 0
    user_seats.each do |x|
      total += x.screening.price
    end
    self.total_price = total
    self.save
  end

end

app/models/cinema.rb
class Cinema < ApplicationRecord
  has_many :showplaces
  has_many :movies, through: :showplaces
  has_many :screenings, through: :showplaces

  validates :latitude, :longitude, presence: true

  mount_uploaders :photos, CinemaPicturesUploader
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :showplaces
  has_many :cinemas, through: :showplaces
  has_many :screenings, through: :showplaces

  mount_uploaders :photos, MoviePicturesUploader
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :reservation
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users
end

app/models/screening.rb
class Screening < ApplicationRecord

  belongs_to :showplace, :dependent => :destroy
  belongs_to :movie
  belongs_to :cinema

  has_many :seats

  after_create :create_seats

  def create_seats
    rows = ("A".."R")
    nums = (1..18)
    rows.each do |row|
      nums.each do |num|
        Seat.create(screening_id: self.id, row_number: row, seat_number: num)
      end
    end
  end
end

app/models/seat.rb
class Seat < ApplicationRecord
  has_many :seat_bookings
  has_many :bookings, through: :seat_bookings
  belongs_to :screening, :dependent => :destroy

end

app/models/seat_booking.rb
class SeatBooking < ApplicationRecord
  belongs_to :seat
  belongs_to :booking
end

app/models/showplace.rb
class Showplace < ApplicationRecord
  belongs_to :movie
  belongs_to :cinema
  has_many :screenings
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]
  belongs_to :role

  validates_presence_of :username
  validates :email, uniqueness:{ message: "Your email has already been taken!"}
  validates :email, presence: { message: "You need to type in an email!"}

  def assign_role
    self.role = Role.find_by(name: "Customer") unless self.role
  end


  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.username = auth.info.name
      user.role_id = Role.find_by_name("Customer").id
        # assuming the user model has a name
      # user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end
end

app/controllers/cinemas_controller.rb
class CinemasController < ApplicationController

  def index
    @q = Cinema.ransack(params[:q])
    if params[:q].nil?
      @cinemas = Cinema.all
    else
      @cinemas = @q.result
    end
  end

  def show
    @cinema = Cinema.find(params[:id])
    @movies = @cinema.movies
  end

  def new
    @cinema = Cinema.new
  end

  def create
    @cinema = Cinema.new(cinema_params)
    if @cinema.save
      redirect_to cinemas_path
    else
      render 'new'
    end
  end

  def edit
    @cinema = Cinema.find(params[:id])
    @showplace = Showplace.new
  end

  def update
     @cinema = Cinema.find(params[:id])
     @cinemas = Cinema.all
     if @cinema.update(cinema_params)
        redirect_to cinemas_path
     else
        render 'edit'
     end
  end

 def destroy
    @cinema = Cinema.find(params[:id])
    @cinema.destroy

    redirect_to root_path
  end


 private
    def cinema_params
      params.require(:cinema).permit(:cinema_name, :contact, :address, :state, :company, :cinema_id, :longitude, :latitude, {photos:[]}, :q)
    end


end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/braintree_helper.rb
module BraintreeHelper
end

app/helpers/cinemas_helper.rb
module CinemasHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/screenings_helper.rb
module ScreeningsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/seats_helper.rb
module SeatsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cinemas/_form.html.erb
<!-- partial f for new.html.erb and edit.html.erb -->

<p>
  <%= f.label :cinema_name %><br>
  <%= f.text_field :cinema_name, id:"text" %>
</p>

<p>
  <%= f.label :contact %><br>
  <%= f.text_field :contact, id:"text" %>
</p>

<p>
  <%= f.label :address %><br>
  <%= f.text_area :address, id:"text" %>
</p>

<p>
  <%= f.label :state %><br>
  <%= f.text_field :state, id:"text" %>
</p>

<p>
  <%= f.label :company %><br>
  <%= f.text_field :company, id:"text" %>
</p>

<p>
  <%= f.label :longitude %><br>
  <%= f.text_field :longitude, id:"text" %>
</p>

<p>
  <%= f.label :latitude %><br>
  <%= f.text_field :latitude, id:"text" %>
</p>

<%= f.file_field :photos, multiple: true %>


<p>
  <%= f.submit "submit cinema info", id:"text" %>
</p>

app/views/cinemas/edit.html.erb
<div class="row">
  <div class-"col-md-8 col-md-offset-2 col-xs-8 col-xs-offset-2">
    <h1 class="text-center">
      Edit Your Cinema
    </h1>
  </div>
</div>
<div class="row">
  <div class="col-md-8 col-md-offset-2 col-xs-8 col-xs-offset-2">
    <div class="col-md-6 col-xs-6 col-sm-6">
      <%= form_for [:admin, @cinema] do |form| %>
       <%= render partial: 'form', locals: {f: form}%>

      <% end %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-8 col-md-offset-2 col-xs-8 col-xs-offset-2 text-center">
    <%= link_to "Delete Cinema", admin_cinema_path(@cinema), method: :delete, data: {confirmation: "Are you sure?"}, class: "btn btn-danger" %>
  </div>
</div>

<%= link_to 'Back', root_path %>

app/views/cinemas/index.html.erb
<div class="container-fluid theatre-container">
  <div class="container container-pad" id="property-listings">
  <!-- please change the first two lines ADRIAN -->
    <div class="row">
      <div class="col-md-12">
        <h1 class="text-center">
          Theatres
        </h1>
      </div>
    </div>
  </div>
</div>

<% @cinemas.each do |cinema| %>
    <div class="container-fluid theatre-container" style="background-color:#e8e8e8">
     <div class="container container-pad" id="property-listings">
       <div class='cinema-index-name-container'>
         <center>
             <h4 class="media-heading cinema-index-name-container ">
               <%= link_to "#{cinema.cinema_name}", cinema_path(cinema)%>
             </h4>
        </center>
       </div>
          <div class="row">
            <div class="col-sm-4">
              <!-- Begin Listing: 609 W GRAVERS LN-->
              <div class="brdr bgc-fff pad-10 box-shad btm-mrg-20 property-listing">
                <div class="media">
                 <%= image_tag cinema.photos.first.url, alt: "stack photo", class: "img" %>
                </div>
              </div>
            </div>

            <div class="col-sm-8">
              <div class="media-body fnt-smaller">
                <p class="hidden-xs">Address: <%= cinema.address %></p>
                <p class='now-showing-movies'> Now Showing Movies </p>
                <p>
                  <% cinema.movies[0..2].each do |movie|%>
                    <%= image_tag movie.photos.first.thumb, class: "cinema-show-movie-pic"%>
                <% end %>
                <% if current_user.role.name == "Admin"%>
                  <%= link_to 'Edit', edit_admin_cinema_path(cinema), class: 'btn btn-mini btn-success' %>
                  <%= link_to 'Destroy', admin_cinema_path(cinema), method: :delete, class: 'btn btn-mini btn-danger', data: { confirm: 'Are you sure?' } %>
                <% end %>
                </p>

              </div>
            </div>
          </div>
      </div>
    </div>
<%end%>

<!-- End Listing-->

<% if current_user.role.name == "Admin" %>
    <%= link_to 'New cinema', new_admin_cinema_path %>
    <%= link_to 'Back', root_path %>
<% end %>

app/views/cinemas/new.html.erb
<h1>New Cinema</h1>


<%= form_for [:admin, @cinema], html: {multiport: true} do |form| %>

  <%= render partial: 'form', locals: {f: form} %>
<% end %>

<%= link_to 'Back', root_path %>

app/views/cinemas/show.html.erb
<!-- PICTURE HERE -->
<div class="container" id='cinema-show-container'>
    <div class="jumbotron">
      <div class="row">
          <div>
              <div class="col-sm-4">
                 <%= image_tag @cinema.photos.first.url, alt: "stack photo", class: "img" %>
              </div>

              <div class="col-sm-8">
                  <div class="container " style="border-bottom:1px solid black">
                    <h2>Cinema: <%= @cinema.cinema_name%></h2>
                  </div>
                    <hr>
                  <ul class="container details">
                    <li><p><span class="glyphicon glyphicon-earphone one" style="width:50px;"></span>Contact: <%= @cinema.contact%></p></li>
                    <li><p><span class="glyphicon glyphicon-home" style="width:50px;"></span>Address: <%= @cinema.address %></p></li>
                    <li><p><span class="glyphicon glyphicon-map-marker one" style="width:50px;"></span>State: <%= @cinema.state %></p></li>
                    <li><p><span class="glyphicon glyphicon-briefcase" style="width:50px;"></span>Company: <%= @cinema.company %> </p></li>
                  </ul>
              </div>
          </div>
      </div>
    </div>
</div>
<% if current_user.role.name == "Admin"%>
  <%= link_to 'Edit', edit_admin_cinema_path(@cinema) %>
  <%= link_to 'Back', root_path %>
<% end %>

<div class="container" id='cinema-show-container'>
    <div class="jumbotron">
      <div class="row">
          <%@cinema.movies.each do |movie| %>
              <div class="movies-in-cinema">
                  <p id='cinema-movie-title'><%=movie.title%></p>
                  <% movie.showplaces.where(cinema_id: @cinema.id).each do |showplace|%>
                      <% showplace.screenings.group_by(&:start_date).each do |date, x|%>
                          <div class="col-md-12 col-sm-12" style="border: 2px solid black">
                            <p><%= date.strftime("%A")%></p>
                            <p>
                            <% x.each do |z| %>
                              <%=link_to "#{z.start_time.strftime('%H:%M')}", book_seats_path(z.id) %>
                            <% end %>
                            </p>
                          </div>
                      <% end %>
                  <% end %>
              </div>
          <%end%>
        </div>
    </div>
</div>