config/routes.rb
Rails.application.routes.draw do


  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }


  scope '/admin' do
    resources :users
  end

  resources :roles


  root "welcome#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # scope '/admin' do
  #   resources :cinemas, except: [:show, :index]
  # end

  resources :cinemas, only: [:show, :index]
  resources :movies, only: [:show, :index]

  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy'
  end

  scope '/admin', as: 'admin' do
    resources :cinemas, except: [:show, :index]
    resources :movies, except: [:show, :index]
    resources :showplaces do
      resources :screenings
    end
  end

  resources :search, only: :get

  get "search" => "search#index"

  get "/coming_soon" => "movies#coming_soon", as: "coming_soon"
  get "/showing_now" => "movies#showing_now", as: "showing_now"

  get "/screenings/:screening_id/seats" => "seats#index", as: "book_seats"

  resources :screenings do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: :show

  get 'bookings/:booking_id/braintree/new' => "braintree#new", as: "braintree_pay"
  post 'bookings/:booking_id/braintree/checkout' => "braintree#checkout", as: "braintree_paying"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    # user ||= User.new # guest user (not logged in)
    # if user.admin?
    #   can :manage, :all
    # else
    #   can :read, :all
    # end

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  belongs_to :user
         def self.create_with_omniauth(auth_hash)
     auth = Authentication.new(provider: auth_hash["provider"], uid: auth_hash["uid"], token: auth_hash["credentials"]["token"])
  end

  def update_token(auth_hash)
    self.token = auth_hash["credentials"]["token"]
    self.save
  end
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_many :seat_bookings
  has_many :seats, through: :seat_bookings
  belongs_to :screening
  belongs_to :user

  def set_total_price(user_seats)
    total = 0
    user_seats.each do |x|
      total += x.screening.price
    end
    self.total_price = total
    self.save
  end

end

app/models/cinema.rb
class Cinema < ApplicationRecord
  has_many :showplaces
  has_many :movies, through: :showplaces
  has_many :screenings, through: :showplaces

  validates :latitude, :longitude, presence: true

  mount_uploaders :photos, CinemaPicturesUploader
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :showplaces
  has_many :cinemas, through: :showplaces
  has_many :screenings, through: :showplaces

  mount_uploaders :photos, MoviePicturesUploader
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :reservation
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users
end

app/models/screening.rb
class Screening < ApplicationRecord

  belongs_to :showplace, :dependent => :destroy
  belongs_to :movie
  belongs_to :cinema

  has_many :seats

  after_create :create_seats

  def create_seats
    rows = ("A".."R")
    nums = (1..18)
    rows.each do |row|
      nums.each do |num|
        Seat.create(screening_id: self.id, row_number: row, seat_number: num)
      end
    end
  end
end

app/models/seat.rb
class Seat < ApplicationRecord
  has_many :seat_bookings
  has_many :bookings, through: :seat_bookings
  belongs_to :screening, :dependent => :destroy

end

app/models/seat_booking.rb
class SeatBooking < ApplicationRecord
  belongs_to :seat
  belongs_to :booking
end

app/models/showplace.rb
class Showplace < ApplicationRecord
  belongs_to :movie
  belongs_to :cinema
  has_many :screenings
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]
  belongs_to :role

  validates_presence_of :username
  validates :email, uniqueness:{ message: "Your email has already been taken!"}
  validates :email, presence: { message: "You need to type in an email!"}

  def assign_role
    self.role = Role.find_by(name: "Customer") unless self.role
  end


  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.username = auth.info.name
      user.role_id = Role.find_by_name("Customer").id
        # assuming the user model has a name
      # user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/braintree_helper.rb
module BraintreeHelper
end

app/helpers/cinemas_helper.rb
module CinemasHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/seats_helper.rb
module SeatsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KIV</title>

    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="An experimental demo where a 3D perspective preview is shown for a selected seat in a cinema room." />
    <meta name="keywords" content="cinema, seat booking, seating plan, perspective, 3d" />
    <meta name="author" content="Codrops" />

      <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

   <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

   <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

   <!-- Special version of Bootstrap that only affects content wrapped in .bootstrap-iso -->
    <link rel="stylesheet" href="https://formden.com/static/cdn/bootstrap-iso.css" />

   <!--Font Awesome (added because you use icons in your prepend/append)-->
    <link rel="stylesheet" href="https://formden.com/static/cdn/font-awesome/4.4.0/css/font-awesome.min.css" />

   <!-- Inline CSS based on choices in "Settings" tab -->
    <style>.bootstrap-iso .formden_header h2, .bootstrap-iso .formden_header p, .bootstrap-iso form{font-family: Arial, Helvetica, sans-serif; color: black}.bootstrap-iso form button, .bootstrap-iso form button:hover{color: white !important;} .asteriskField{color: red;}</style>


    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>

    <script src="https://maps.googleapis.com/maps/api/js"></script>
    <script src="js/jquery.js"></script>
    <!-- Load the Client component. -->
      <script src="https://js.braintreegateway.com/web/3.6.3/js/client.min.js"></script>

      <!-- Load the Hosted Fields component. -->
      <script src="https://js.braintreegateway.com/web/3.6.3/js/hosted-fields.min.js"></script>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'film.ico' %>
  </head>

  <body id="bg-image">
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= image_tag 'V.png', class:"logo" %>

        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
          <ul class="nav navbar-nav">

            <li><a href="/">Home</a></li>
            <li><%= link_to "Now Showing", showing_now_path %></li>
            <li><%= link_to "Coming Soon", coming_soon_path %></li>
            <li><%= link_to "Theatres", cinemas_path %></li>


          </ul>
          <ul class="nav navbar-nav navbar-right">


            <% if user_signed_in? %>
              <div class="dropdown">
                <button class="dropbtn nav-text"><%= current_user.username.capitalize %></button>
                <div class="dropdown-content">
                  <li><%= link_to "Edit profile", edit_user_registration_path %></li>
                  <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
                </div>
              </div>
            <% else %>
              <li><%= link_to "Sign up", new_user_registration_path %></li>
              <li><%= link_to "Login", new_user_session_path %></li>
            <% end %>

            <% flash.each do |name, msg| %>
              <%= content_tag :div, msg, id: "flash_#{name}" %>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>



    <%= yield %>
<!--
    <footer class="container-fluid text-center footer">
      <p style="">Footer Text</p>
    </footer> -->




  </body>
</html>

app/views/layouts/seats.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KIV</title>

    <meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="An experimental demo where a 3D perspective preview is shown for a selected seat in a cinema room." />
		<meta name="keywords" content="cinema, seat booking, seating plan, perspective, 3d" />
		<meta name="author" content="Codrops" />
		<!-- <link rel="stylesheet" type="text/css" href="css/normalize.css" />
		<link rel="stylesheet" type="text/css" href="css/demo.css" />
		<link rel="stylesheet" type="text/css" href="css/component.css" /> -->
		<!-- <script src="js/modernizr-custom.js"></script> -->


    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


    <%= csrf_meta_tags %>
    
    <%= stylesheet_link_tag "demo" %>
    <%= stylesheet_link_tag "normalize" %>
    <%= stylesheet_link_tag "component" %>

    <%= favicon_link_tag 'film.ico' %>

    <script src="https://js.braintreegateway.com/v2/braintree.js"></script>
  </head>

  <body>


    <%= yield %>
<!--
    <footer class="container-fluid text-center footer">
      <p style="">Footer Text</p>
    </footer> -->




  </body>
</html>